# Q1: Import numpy library

In [3]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [62]:
seq = np.linspace(1, 5, 15) 
print([round(num, 2) for num in seq])

[1.0, 1.29, 1.57, 1.86, 2.14, 2.43, 2.71, 3.0, 3.29, 3.57, 3.86, 4.14, 4.43, 4.71, 5.0]


# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [11]:
arr1 = [1.1, 2.1, 3.1]
arr2 = [4.1, 5.1, 6.1]
arr3 = [7.1, 8.1, 9.1]
arr4 = [10.1, 11.1, 12.1]

arr3d = np.array([[arr1, arr2], [arr3, arr4]])
print(arr3d)

[[[ 1.1  2.1  3.1]
  [ 4.1  5.1  6.1]]

 [[ 7.1  8.1  9.1]
  [10.1 11.1 12.1]]]


# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [20]:
arr4d = arr3d.reshape(1, 2, 2, 3)
print(arr4d)

[[[[ 1.1  2.1  3.1]
   [ 4.1  5.1  6.1]]

  [[ 7.1  8.1  9.1]
   [10.1 11.1 12.1]]]]


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [22]:
intArr = arr4d.astype(int)
print(intArr)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]


# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [23]:
for item in np.nditer(intArr):
    print(item)




1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [41]:
sli = intArr[0, 1, 0, 1:2]
print(sli)



[8]


# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [42]:
sl = intArr[0, 0, 1, 1:3]
print(sl)


[5 6]


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [44]:
sea = np.where(intArr == 8)
print(sea)

(array([0]), array([1]), array([0]), array([1]))


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [45]:
resh = intArr.reshape(2, 3, 2)
print(resh)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [49]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

#join = np.hstack((arr1, arr2))
join = np.concatenate((arr1, arr2))
print(join)

[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


# Q12.2: Join the arrays along rows with axis = 1 

In [50]:
join1 = np.concatenate((arr1, arr2), axis=1)
print(join1)

[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']]


# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [61]:
spl = np.split(join,2, axis=1)
print(spl)

[array([['A'],
       ['E'],
       ['C'],
       ['G']], dtype='<U1'), array([['B'],
       ['F'],
       ['D'],
       ['H']], dtype='<U1')]
